# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Max Mathys
email: max.mathys@gmail.com
description: I do design and internet sideprojects
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mmathys.github.io" # the base hostname & protocol for your site
twitter_username: pakkojuoda
github_username:  mmathys

# Build settings
markdown: kramdown

# post defaults

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "work"
      whatever: "this is working"
      post: true
